License Check v0.1
DigiCorpLabs/license-gate pull request #1
Opened 2024-11-22 11:09 UTC by biinui

2025-01-13 06:35 UTC, SmartArray commented
Sorry, I must have forgotten to review this.

Can you quickly add an API route that returns a JWT token? Here are the details for it:

## Details for license JWT signature creation

I created this script to create a JWT for a specific license code. The dependencies this uses are `fast-jwt`, `uuid` and `ms`.
The below script works just in command line, you can try it out immediately.

For that to work, you have to create a private + public key using these two instructions:

```bash
# Here we create a private key
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048

# and derive a public key from the private key
openssl rsa -pubout -in private_key.pem -out public_key.pem
``` 

All you have to do at our precious LicenseGate fork is to create a route that accepts a license code (uuid) and returns a JWT token.

In the token payload you have to fill in the gaps:

- `md`: max devices
- `mu`: max users (you can statically set this to a number of your choice for now, maybe 2 * max devices)
- `exp`: license expiry timestamp (seconds since 1970)
- `idc`: license code (uuid)
- `idr`: record id (default: 1): every time the license info is updated, we have to bump this. I don't care whether you generate the JWT beforehand and put it in a database table, or if you generate it on the fly. However, if the customer pays to increase their license seats (max devices), thus creating a new version/revision of the license, this field need to increase by one. DGMV-IAM will only accept license codes where this field has increased by one.

That's it!

I bet the best is to extract the class `TokenService` and call it like that: 

```javascript
const token = new TokenService(privateKey).createJwt({
  md: 100,
  mu: 200,
  // ...
});
``` 

```javascript
import { createSigner } from 'fast-jwt';
import { basename, relative } from 'node:path';
import { readFileSync } from 'node:fs';
import { v4 as uuidv4 } from 'uuid';
import ms from 'ms';

class TokenService {
  constructor(privateKey) {
    this.privateKey = privateKey;
  }

  createJwt(payload) {
    const sign = createSigner({
      key: this.privateKey,
      algorithm: 'RS256' // Use the appropriate algorithm for your key
    });

    return sign(payload);
  }
}

const [nodeBin, nodeScript, ...args] = process.argv;

if (args.length !== 2) {
  console.error(`Usage: ${basename(nodeBin)} ${relative(process.cwd(), nodeScript)} <path-to-private-key> <json-payload>`);
  console.error();

  console.error(`JSON Payload Template (1yr):`);
  const template = {
    idc: uuidv4(),
    idr: 1,
    exp: Math.trunc((Date.now() + ms('1 year')) / 1000),
    mu: 10,
    md: 10,
  };

  console.error(`'${JSON.stringify(template)}'`);

  console.error();
  console.error(`Description of fields:`);
  console.error(`* idc: Unique License Code (uuid)`);
  console.error(`* idr: License Revision of this specific license code (reissuance)`);
  console.error(`* exp: License Expiry Date (seconds since Unix)`);
  console.error(`* mu: maximum allowed Users`);
  console.error(`* md: maximum allwoed Devices`);
  console.error();

  process.exit(1);
}

const [privateKeyPath, jsonPayload] = args;

// Read private key
const privateKey = readFileSync(privateKeyPath, 'utf-8');

// Parse payload
const payload = JSON.parse(jsonPayload);

if (!payload.idc) {
  console.warn("No 'idc' (license uuid) supplied in license, generating one");
  payload.idc = uuidv4();
}

if (!payload.exp) {
  console.warn("No 'exp' (expiryDate) supplied in license, generating one [+ 1yr]");
  payload.exp = Math.trunc((Date.now() + ms('1 year')) / 1000);
}

if (!payload.idr) {
  const now = Math.trunc(Date.now() / 1000);
  console.warn(`No 'idr' (license revision) supplied in license, generating one [${now}]`);
  payload.idr = now;
}

if (!payload.mu) {
  console.warn(`No 'mu' (max users) supplied in license, generating one [10]`);
  payload.mu = 10;
}

if (!payload.md) {
  console.warn(`No 'md' (max devices) supplied in license, generating one [10]`);
  payload.mu = 10;
}

// Create token
const token = new TokenService(privateKey).createJwt(payload);

console.log();
console.log(`Created license token:`);
console.log();
console.log(`${token}`);
console.log();

```

Let me know if there are any difficulties with this above idea or if you have any questions 🙃

2025-01-14 06:00 UTC, SmartArray requested changes
Thanks for the hard work!

We are almost there!

2025-01-14 06:00 UTC, SmartArray commented on backend/prisma/schema.prisma
> +  maxDevices     Int      @default(0)
Can you elaborate why the UserModel needs maxDevices and currentDevices?

2025-01-14 06:00 UTC, SmartArray commented on backend/prisma/schema.prisma
> +  idc       String    @unique
If the code is set to @unique, it will only allow one code to live in the database.

IMO, It is better to use:

```prisma
@@unique([idc, idr], name: "license-jwt-id")
```

Or is there a specific reason why you are using an atomic @unique, e.g. are you deleting the previous entry before inserting a revisioned version of the token?

2025-01-14 06:00 UTC, SmartArray commented on backend/src/controller/verify-license.ts
> +    idc: `${license.licenseKey}/${license.userId}`,
Can you elaborate why we are appending `license.userId` to the key? Better to use another field to store the userId, no?

2025-01-14 06:00 UTC, SmartArray commented on backend/src/controller/verify-license.ts
> +    exp: exp ?? null,
This is dangerous, can we make the default a year from now()?
Otherwise the customer might - under circumstances - receive a license that is valid for the rest of their life 👀

2025-01-14 06:00 UTC, SmartArray commented on backend/src/routers/public/license-verify.controller.ts
> +  jwt?: string;
Perfect, thank you!

2025-01-14 06:00 UTC, SmartArray commented on backend/src/routers/public/token.controller.ts
> +    const payload = JSON.parse(
Hahaha, why can't this be:

```typescript
const payload: any = { idc: licenseCode }
```

or better yet, with an interface definition?

2025-01-14 06:00 UTC, SmartArray commented on backend/src/routers/public/token.controller.ts
> +    return new TokenService(privateKey).createJwt(payload);
Oh wait, so this is the old version of the endpoint that accepts any licenseCode, right?
If so, maybe we should remove it

2025-01-14 11:21 UTC, biinui commented on backend/prisma/schema.prisma
> +  maxDevices     Int      @default(0)
This is outdated. I'll remove 😁

2025-01-14 11:22 UTC, biinui commented on backend/prisma/schema.prisma
> +  idc       String    @unique
Oh good point, so we insert a new `License` every time a `License` is revised.
I'll follow your suggestion 😁

2025-01-14 11:24 UTC, biinui commented on backend/src/controller/verify-license.ts
> +    idc: `${license.licenseKey}/${license.userId}`,
The "complete" license for verify license endpoint is `{userId}/{licenseCode}`
Example: GET `license/{userId}/{licenseCode}/verify`

2025-01-14 11:24 UTC, biinui commented on backend/src/controller/verify-license.ts
> +    exp: exp ?? null,
I'll fix this, thanks 😁

2025-01-14 11:25 UTC, biinui commented on backend/src/routers/public/token.controller.ts
> +    const payload = JSON.parse(
Good catch, this file is for deletion. 😁

2025-01-14 11:26 UTC, biinui commented on backend/src/routers/public/token.controller.ts
> +    return new TokenService(privateKey).createJwt(payload);
Yes, we transferred the logic to verify-license controller.
I'll remove this file to reduce confusion. 😁

2025-01-14 12:48 UTC, merged